[package]
name = "yash-syntax"
version = "0.1.0"
authors = ["WATANABE Yuki <magicant@wonderwand.net>"]
edition = "2018"
description = "Yash shell language syntax definition and parser"
# documentation = "https://yash.osdn.jp/doc/"
# readme = "README.md"
# homepage = "https://yash.osdn.jp/"
repository = "https://github.com/magicant/yash-rs"
license = "GPL-3.0-or-later"
# license-file = "../LICENSE"
keywords = ["posix", "shell"]
categories = ["command-line-utilities", "parser-implementations"]
publish = false

[dependencies]
async-trait = "0.1.50"
futures = "0.3.8"
itertools = "0.9.0"
